### ISSUE TITLE
Using extra data

### ISSUE THREAD

**Issue by shenberg** [omarperacha/TonicNet#1]
Seems like you're comparing the NLL of your model which has chord data available at test time to the NLL of music transformer which doesn't

**Comment by omarperacha** [comment]
TonicNet has to first predict the chord data before predicting the notes. Chord data is itself derived directly from the existing dataset so there’s no outside data per se - so it’s most accurate to think of it as an augmented dataset rather than extra data.

Let me know if there’s more I can answer or take a look at the detailed explanation in the paper preprint.

**Comment by shenberg** [comment]
I looked at the explanation and at the code. say you are comparing two language models, predicting text without spaces and punctuations, one with. Are those equivalent tasks?

**Comment by omarperacha** [comment]
I see your point. The difference in a musical context is that the chords at each timestep (as I have treated them) are a direct consequence of the notes only - whereas punctuation can not necessarily be extracted from text only.

I also report loss averaged over the notes only, disregarding the chords, using them as a feature to aid loss reduction on the notes. So NLL is reported on the exact same sequence as music transformer, the chords are a performance helper. That’s my main finding here, and if music transformer introduced the chords as a helper it should improve performance with that model too. I didn’t have the chance to test with relative attention due to resource constraints.

My hope is that these findings can help people get better results on their own music models, by showing a way to very effectively augment the dataset.

**Comment by shenberg** [comment]
A detailed blog-post on the subject: https://sjmielke.com/comparing-perplexities.htm
